"""
@Author: Bo Molenaar
@Date: 22 March 2023

This script can be ran after uber_serda.py to generate bootstrapped segments for SERDA v1 story tasks.
It uses ASR output to get timestamps for end of utterances automatically.
Ideally these correspond to the end of the sentences/lines in the reading prompts.

Input: 
1.  path to directory of story task audio
2.  path to directory of ASR output for these recordings
3.  path to directory to place audio segments

Output:
Segmented audio in dir 3.
"""

# create a dict with rec_id, story audio, story AO

# then run segmentation on each entry

def segment_story(full_rec_path, rec_segments_path, rec_AO):
    """
    Takes a story audio file and matches it to its story prompt.
    Then, bootstrapped segments generated by WhisperX ASR are searched 
    to identify start/end timestamps in the audio for each line in the prompt.
    
    """
    # TODO:
    # stories will be segmented based on WhisperX ASR output
    # this means we need timestamps for each segment in the JSON
    # --> match prompt line to id in JSON
